#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
    path: /logout


# config/routes/dev/twig.yaml
_errors:
    resource: '@TwigBundle/Resources/config/routing/errors.xml'
    prefix:   /_error