<?php


namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
//class contenant la logique du formulaire
class EventType extends AbstractType
{
public function buildForm(FormBuilderInterface $builder, array $options)
{


    $builder
        ->add('title', TextType::class, [
            'label' => 'Nom de l\'évènement',
             ])
        ->add('place', TextType::class, [
            'label' => 'Lieu de l\'évènement',
             ])
        ->add('organisator', TextType::class, [
            'label' => 'Organisateur de l\'évènement',
            ])
        ->add('description', TextareaType::class, [
            'label' => 'Description de l\'évènement',
             ])
        ->add('date',DateType::class, [
            'label' => 'Date de l\'évènement',
            'placeholder' => [
                'year' => 'Année', 'month' => 'Mois', 'day' => 'Jour',
            ],
            'format' => 'yyyy-MM-dd'
             ])
        ->add('emailcontact',EmailType::class, [
            'label' => 'Email de contact',
             ])
        ->add('phonecontact', TextType::class, [
            'label' => 'Téléphone de contact',
              ])
        ->add('photo',FileType::class, [
            'data_class' => null,
            'label' => 'Photo de l\'évènement',
            ])
        ;
   // parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
}
}